// Tüm kategoriler ve ürünler
const fullCategoriesData = [
  {
    "id": 1,
    "title": "Nokta dedektor",
    "slug": "nokta-dedektor",
    "products": [
      {
        "id": 1,
        "name": "Nokta Makro Simplex+ WHP",
        "slug": "nokta-makro-simplexplus-whp",
        "description": "Nokta Makro Simplex+ WHP gelişmiş dedektör teknolojisiyle üstün performans sunar.",
        "shortDescription": "Nokta Makro Simplex+ WHP ile hazine avında fark yaratın.",
        "sku": "SKU-42553",
        "price": 47981,
        "originalPrice": 47981,
        "discountPercentage": 0,
        "stock": 61,
        "images": ["/images/nokta-makro-simplexplus-whp.jpg"],
        "categories": ["nokta"],
        "brand": "Nokta",
        "specifications": {
          "frekans": "40kHz",
          "ağırlık": "1.6 kg",
          "batarya": "AA"
        },
        "variants": [],
        "isActive": true,
        "isFeatured": true,
        "isNew": true,
        "isOnSale": false,
        "weight": 1.4763449736550327,
        "dimensions": "35x32x14 cm",
        "width": 31,
        "height": 12,
        "unit": "adet",
        "tags": ["nokta", "dedektör"],
        "rating": 4.5,
        "reviewCount": 189,
        "seoTitle": "Nokta Makro Simplex+ WHP - En İyi Dedektör Fiyatı ve Özellikleri",
        "seoDescription": "Nokta Makro Simplex+ WHP modeli, en son teknoloji ile tasarlanmış bir dedektördür.",
        "metaKeywords": "Nokta Makro Simplex+ WHP, dedektör, hazine, metal, arama"
      },
      {
        "id": 2,
        "name": "Nokta Makro The Legend",
        "slug": "nokta-makro-the-legend",
        "description": "Nokta Makro The Legend gelişmiş dedektör teknolojisiyle üstün performans sunar.",
        "shortDescription": "Nokta Makro The Legend ile hazine avında fark yaratın.",
        "sku": "SKU-55230",
        "price": 25403,
        "originalPrice": 30483,
        "discountPercentage": 20,
        "stock": 31,
        "images": ["/images/nokta-makro-the-legend.jpg"],
        "categories": ["nokta"],
        "brand": "Nokta",
        "specifications": {
          "frekans": "40kHz",
          "ağırlık": "2.0 kg",
          "batarya": "AA"
        },
        "variants": [],
        "isActive": true,
        "isFeatured": true,
        "isNew": true,
        "isOnSale": true,
        "weight": 1.5914236648593478,
        "dimensions": "49x23x17 cm",
        "width": 34,
        "height": 18,
        "unit": "adet",
        "tags": ["nokta", "dedektör"],
        "rating": 4.2,
        "reviewCount": 155,
        "seoTitle": "Nokta Makro The Legend - En İyi Dedektör Fiyatı ve Özellikleri",
        "seoDescription": "Nokta Makro The Legend modeli, en son teknoloji ile tasarlanmış bir dedektördür.",
        "metaKeywords": "Nokta Makro The Legend, dedektör, hazine, metal, arama"
      },
      {
        "id": 3,
        "name": "Nokta Makro Anfibio Multi",
        "slug": "nokta-makro-anfibio-multi",
        "description": "Nokta Makro Anfibio Multi gelişmiş dedektör teknolojisiyle üstün performans sunar.",
        "shortDescription": "Nokta Makro Anfibio Multi ile hazine avında fark yaratın.",
        "sku": "SKU-70619",
        "price": 46419,
        "originalPrice": 48739,
        "discountPercentage": 5,
        "stock": 61,
        "images": ["/images/nokta-makro-anfibio-multi.jpg"],
        "categories": ["nokta"],
        "brand": "Nokta",
        "specifications": {
          "frekans": "10kHz",
          "ağırlık": "2.4 kg",
          "batarya": "Li-ion"
        },
        "variants": [],
        "isActive": true,
        "isFeatured": true,
        "isNew": true,
        "isOnSale": true,
        "weight": 1.6451364883918969,
        "dimensions": "36x23x20 cm",
        "width": 24,
        "height": 18,
        "unit": "adet",
        "tags": ["nokta", "dedektör"],
        "rating": 3.5,
        "reviewCount": 82,
        "seoTitle": "Nokta Makro Anfibio Multi - En İyi Dedektör Fiyatı ve Özellikleri",
        "seoDescription": "Nokta Makro Anfibio Multi modeli, en son teknoloji ile tasarlanmış bir dedektördür.",
        "metaKeywords": "Nokta Makro Anfibio Multi, dedektör, hazine, metal, arama"
      }
    ]
  },
  {
    "id": 2,
    "title": "Minelab",
    "slug": "minelab-dedektor",
    "products": [
      {
        "id": 1,
        "name": "Minelab 11\" Coil, Commander Mono",
        "slug": "minelab-11-coil-commander-mono",
        "description": "Minelab 11\" Coil, Commander Mono yüksek performanslı bir metal dedektörüdür.",
        "shortDescription": "Minelab 11\" Coil, Commander Mono gelişmiş arama teknolojisine sahiptir.",
        "sku": "MIN-1001",
        "price": 14625,
        "originalPrice": 12657,
        "discountPercentage": 16,
        "stock": 35,
        "images": ["https://example.com/images/minelab-11-coil-commander-mono.jpg"],
        "categories": ["Dedektör", "Minelab"],
        "brand": "Minelab",
        "specifications": {
          "frequency": "Variable",
          "waterproof": true,
          "batteryLife": "8 saat"
        },
        "variants": [],
        "isActive": true,
        "isFeatured": true,
        "isNew": false,
        "isOnSale": false,
        "weight": "1.5 kg",
        "dimensions": "120x30x20 cm",
        "width": 30,
        "height": 120,
        "unit": "adet",
        "tags": ["metal dedektör", "minelab", "arama cihazı"],
        "rating": 4.2,
        "reviewCount": 88,
        "seoTitle": "Minelab 11\" Coil, Commander Mono | Minelab Dedektör",
        "seoDescription": "Minelab 11\" Coil, Commander Mono modeli ile en zorlu koşullarda bile üstün metal algılama performansı.",
        "metaKeywords": "Minelab 11\" Coil, Commander Mono, metal dedektör, minelab, arama cihazı"
      }
    ]
  }
];

module.exports = fullCategoriesData;